Bilet10/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bilet10.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    [Authorize(Roles = "SuperAdmin")]

    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bilet10/Areas/Admin/Controllers/OurTeamController.cs
using Bussiness.Abstracts;
using Bussiness.Exceptions;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bilet10.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OurTeamController : Controller
    {
        IOurTeamService _ourTeamService;

        public OurTeamController(IOurTeamService ourTeamService)
        {
            _ourTeamService = ourTeamService;
        }
       
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Index()
        {
            var teams = _ourTeamService.GetAllTeam();
            return View(teams);
        }

        [Authorize(Roles = "SuperAdmin")]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(OurTeam ourTeam)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _ourTeamService.Create(ourTeam);
            }
            catch (NotFoundException ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            catch(FileContentTypeException ex)
            {
                ModelState.AddModelError("PhotoFile", ex.Message);
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "SuperAdmin")]

        public IActionResult Delete(int id)
        {
            _ourTeamService.Delete(id);
            return RedirectToAction("Index");   
        }
        [Authorize(Roles = "SuperAdmin")]

        public IActionResult Update(int id)
        {
            var team=_ourTeamService.GetTeam(x=>x.Id == id);

            return View(team);
        }
        [HttpPost]
        public IActionResult Update(OurTeam team)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _ourTeamService.Update(team.Id,team);
            }
            catch (NotFoundException ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            catch (FileContentTypeException ex)
            {
                ModelState.AddModelError("PhotoFile", ex.Message);
            }
            return RedirectToAction("Index");

        }
    }
}

Bilet10/Controllers/AccountController.cs
using Bilet10.DTOs;
using Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bilet10.Controllers
{
    public class AccountController : Controller
    {
        UserManager<User> _userManager;
        SignInManager<User> _signInManager;
        RoleManager<IdentityRole> _roleManager;

        public AccountController(SignInManager<User> signInManager, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterDto registerDto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            User user=new User()
            {
                Name= registerDto.Name,
                Surname=registerDto.Surname,
                Email=registerDto.Email,
                UserName=registerDto.UserName,
            };
            
            var result= await _userManager.CreateAsync(user,registerDto.Password);
            if(!result.Succeeded)
            {
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View();
            }
       
            await _signInManager.SignInAsync(user, false);
            await _userManager.AddToRoleAsync(user, "Admin");


            return RedirectToAction("Index", "Home");
            
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto login)
        {
            var user = await _userManager.FindByNameAsync(login.EmailOrUserName);
            if(user == null)
            {
                user= await _userManager.FindByEmailAsync(login.EmailOrUserName);
                if( user == null)
                {
                    ModelState.AddModelError("", "Pasword ve ya username duzgun daxil edilmeyib!");
                    return View();
                }
            }
            var result= await _signInManager.CheckPasswordSignInAsync(user,login.Password,true);
            if(result.IsLockedOut)
            {
                ModelState.AddModelError("", "Birazdan yeniden cehd edin!");
            }
            if(!result.Succeeded)
            {
                ModelState.AddModelError("", "Pasword ve ya username duzgun daxil edilmeyib!");
                return View();
            }
            await _signInManager.SignInAsync(user, login.IsRemember);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult LogOut()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> CreateRole()
        {
            IdentityRole role = new IdentityRole("Admin");
            

            IdentityRole role1 = new IdentityRole("SuperAdmin");
            IdentityRole role2 = new IdentityRole("Member");
           await  _roleManager.CreateAsync(role);
           await  _roleManager.CreateAsync(role1);
           await  _roleManager.CreateAsync(role2);
            return Ok();




        }
    }
}

Bilet10/Controllers/HomeController.cs
using Bussiness.Abstracts;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bilet10.Controllers
{
	public class HomeController : Controller
	{
		IOurTeamService _ourTeam;

        public HomeController(IOurTeamService ourTeam)
        {
            _ourTeam = ourTeam;
        }

        public IActionResult Index()
		{
			var teams=_ourTeam.GetAllTeam();
			return View(teams);
		}

		
	}
}

Bilet10/Areas/Admin/Views/OurTeam/Create.cshtml
@using Core.Models
@model OurTeam
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name"  class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Position" class="form-label">Position</label>
            <input asp-for="Position" class="form-control">
            <span asp-validation-for="Position" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>
        
     
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Bilet10/Areas/Admin/Views/OurTeam/Index.cshtml
@using Core.Models
@model List<OurTeam>
@{
    int count = 0;
}
<div class="container">
    <h1>
        Our Teams
        <a class="btn btn-primary" asp-action="Create">Create</a>
    </h1>
</div>
<div class="container">
    
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Position</th>
                <th scope="col">Image</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                count++;
                <tr>
                    
                    <td>@count</td>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Position</td>
                    <td>
                        <img  src="~/Upload/OurTeam/@item.ImgUrl" height="100" width="100"/>
                    </td>
                   <td>
                        <a class="btn btn-warning" asp-action="Update" asp-controller="OurTeam" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="OurTeam" asp-route-id="@item.Id">Delete</a>
                   </td>



                </tr>

            }

        </tbody>
    </table>
</div>

Bilet10/Areas/Admin/Views/OurTeam/Update.cshtml
@using Core.Models
@model OurTeam
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Position" class="form-label">Position</label>
            <input asp-for="Position" class="form-control">
            <span asp-validation-for="Position" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Bilet10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>eBusiness Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: eBusiness - v4.10.0
    * Template URL: https://bootstrapmade.com/ebusiness-bootstrap-corporate-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex justify-content-between">

            <div class="logo">
                <h1><a href="index.html"><span>e</span>Business</a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="~/assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>
                    <li><a class="nav-link scrollto" href="#team">Team</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link scrollto" >@User.Identity.Name</a></li>
                        <li><a class="nav-link scrollto" asp-action="LogOut" asp-controller="account">Log Out</a></li>
                    }
                    else
                    {
                        <li><a class="nav-link scrollto" asp-action="Register" asp-controller="Account">Register</a></li>
                        <li><a class="nav-link scrollto" asp-action="Login" asp-controller="Account">Login</a></li>

                    }
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
            @RenderBody()

    <!-- ======= Footer ======= -->
    <footer>
        <div class="footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="footer-content">
                            <div class="footer-head">
                                <div class="footer-logo">
                                    <h2><span>e</span>Business</h2>
                                </div>

                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.</p>
                                <div class="footer-icons">
                                    <ul>
                                        <li>
                                            <a href="#"><i class="bi bi-facebook"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="bi bi-twitter"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="bi bi-instagram"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="bi bi-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end single footer -->
                    <div class="col-md-4">
                        <div class="footer-content">
                            <div class="footer-head">
                                <h4>information</h4>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
                                </p>
                                <div class="footer-contacts">
                                    <p><span>Tel:</span> +123 456 789</p>
                                    <p><span>Email:</span> contact@example.com</p>
                                    <p><span>Working Hours:</span> 9am-5pm</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end single footer -->
                    <div class="col-md-4">
                        <div class="footer-content">
                            <div class="footer-head">
                                <h4>Instagram</h4>
                                <div class="flicker-img">
                                    <a href="#"><img src="~/assets/img/portfolio/1.jpg" alt=""></a>
                                    <a href="#"><img src="~/assets/img/portfolio/2.jpg" alt=""></a>
                                    <a href="#"><img src="~/assets/img/portfolio/3.jpg" alt=""></a>
                                    <a href="#"><img src="~/assets/img/portfolio/4.jpg" alt=""></a>
                                    <a href="#"><img src="~/assets/img/portfolio/5.jpg" alt=""></a>
                                    <a href="#"><img src="~/assets/img/portfolio/6.jpg" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-area-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="copyright text-center">
                            <p>
                                &copy; Copyright <strong>eBusiness</strong>. All Rights Reserved
                            </p>
                        </div>
                        <div class="credits">
                            <!--
                              All the links in the footer should remain intact.
                              You can delete the links only if you purchased the pro version.
                              Licensing information: https://bootstrapmade.com/license/
                              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=eBusiness
                            -->
                            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer><!-- End  Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>